version: "3.9"

services:
  app:
    image: ${DOCKERHUB_USER}/todoapp:${IMAGE_TAG:-latest}
    environment:
      PORT: 3000
      DB_CLIENT: ${DB_CLIENT:-sqlite}   # o mysql si lo usas en VM
      # ... otras vars que necesites
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -fsS http://localhost:3000/ >/dev/null"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
