version: 2.1

jobs:
  build_and_smoke:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: yarn install --frozen-lockfile || yarn install
      - run:
          name: Smoke test (SQLite + PORT=3000)
          command: |
            export PORT=3000
            export DB_CLIENT=sqlite
            node src/index.js > app.log 2>&1 & APP_PID=$!

            for i in {1..60}; do
              if curl -fsS "http://localhost:${PORT}/" >/dev/null 2>&1; then
                echo "Smoke OK"
                kill $APP_PID || true
                exit 0
              fi
              sleep 1
            done

            echo "App no respondió. Últimas líneas del log:"
            tail -n 200 app.log || true
            kill $APP_PID || true
            exit 1

workflows:
  ci:
    jobs:
      - build_and_smoke
