version: 2.1

jobs:
  build_and_smoke:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: "${DOCKERHUB_USER}/todoapp"
      IMAGE_TAG: "${CIRCLE_SHA1:0:7}"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" -t "${IMAGE_NAME}:latest" .
      - run:
          name: Smoke test (container)
          command: |
            cid=$(docker run -d -e PORT=3000 -p 3000:3000 "${IMAGE_NAME}:${IMAGE_TAG}")
            # espera a que responda
            for i in $(seq 1 30); do
              if curl -fsS http://localhost:3000/ >/dev/null; then echo "SMOKE OK"; break; fi
              sleep 1
            done
            curl -fsS http://localhost:3000/ >/dev/null
            docker logs "$cid" --tail 50 || true
            docker stop "$cid" >/dev/null

  docker_build_and_push:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_NAME: "${DOCKERHUB_USER}/todoapp"
      IMAGE_TAG: "${CIRCLE_SHA1:0:7}"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login
          command: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
      - run:
          name: Build & Push
          command: |
            docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" -t "${IMAGE_NAME}:latest" .
            docker push "${IMAGE_NAME}:${IMAGE_TAG}"
            docker push "${IMAGE_NAME}:latest"
      - run:
          name: Export image tag
          command: echo "export IMAGE_TAG=${IMAGE_TAG}" >> $BASH_ENV

workflows:
  ci_cd:
    jobs:
      - build_and_smoke
      - docker_build_and_push:
          requires: [build_and_smoke]
          filters:
            branches:
              only: [main]
