version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build_and_smoke:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Smoke test
          command: |
            PORT=${PORT:-3000}
            node src/index.js & APP_PID=$!
            for i in {1..30}; do
              curl -fsS "http://localhost:$PORT/" >/dev/null && break
              sleep 1
            done
            curl -fsS "http://localhost:$PORT/" | head -n1
            kill $APP_PID || true
workflows:
  ci:
    jobs:
      - build_and_smoke
